use once_cell::sync::Lazy;
use users::{get_user_by_uid, get_current_uid};

pub static CURR_USER: Lazy<users::User> = Lazy::new(|| {
    get_user_by_uid(get_current_uid()).unwrap()
});

/// A list of all the common logging files in a UNIX machine
pub static LOG_FILES: [&str; 69] = [
    "~/.bash_history",
    "~/.zsh_history",
    "/var/log/syslog",
    "/var/log/messages",
    "/var/log/auth.log",
    "/var/log/secure",
    "/var/log/kern.log",
    "/var/log/daemon.log",
    "/var/log/cron.log",
    "/var/log/boot.log",
    "/var/log/dmesg",
    "/var/log/wtmp",
    "/var/log/btmp",
    "/var/log/lastlog",
    "/var/log/faillog",
    "/var/log/dpkg.log",
    "/var/log/apt/history.log",
    "/var/log/yum.log",
    "/var/log/journal",
    "/run/log/journal",
    "/var/log/audit/audit.log",
    "/var/log/nginx/access.log",
    "/var/log/nginx/error.log",
    "/var/log/apache2/access.log",
    "/var/log/apache2/error.log",
    "/var/log/httpd/access_log",
    "/var/log/httpd/error_log",
    "/var/log/mail.log",
    "/var/log/maillog",
    "/var/log/mysql/error.log",
    "/var/log/mysqld.log",
    "/var/log/postgresql/postgresql.log",
    "/var/log/mongodb/mongod.log",
    "/var/log/redis/redis-server.log",
    "/var/log/elasticsearch/elasticsearch.log",
    "/var/log/supervisor/supervisord.log",
    "/var/log/cron",
    "/var/log/pm-powersave.log",
    "/var/log/docker.log",                                 
    "/var/lib/docker/containers/*/*-json.log",             
    "/var/log/containers/*",                              
    "/var/log/pods/*",                                     
    "/var/log/daemon.log",                                
    "/var/log/containerd.log",                            
    "/run/containerd",                                      
    "/var/log/crio/crio.log",
    "/var/log/crio",                                        
    "/var/log/kubelet.log",
    "/var/log/kube-proxy.log",
    "/var/log/kube-apiserver.log",
    "/var/log/kube-scheduler.log",
    "/var/log/kube-controller-manager.log",
    "/var/log/etcd/etcd.log",
    "/var/log/etcd",                                        
    "/var/log/kubernetes",                                 
    "/var/log/prometheus/*.log",
    "/var/log/grafana/grafana.log",
    "/var/log/node-exporter.log",
    "/var/log/collectd.log",
    "/var/log/php7.4-fpm.log",
    "/var/log/php-fpm.log",
    "/var/log/solr/solr.log",
    "/var/log/cassandra/system.log",
    "/var/log/zookeeper/zookeeper.log",
    "/var/log/uwsgi/app/*.log",
    "/var/log/krb5kdc.log",
    "/var/log/pods/*/*/*.log",
    "/var/log/*",                                          
    "/var/lib/docker/volumes/*/_data/*",                  
]; 
// Thanks https://github.com/sundowndev/covermyass
// Added logs by havij13
